{{- define "go-quai.ingress" }}
- host: rpc.prime.{{- .Values.goQuai.network -}}.quaiscan.io
  http:
    paths:
    - path: /
      pathType: Prefix
      backend:
        service:
          name: prime-{{ include "go-quai.name" $ }}
          port:
            name: http
    - path: /ws
      pathType: Prefix
      backend:
        service:
          name: prime-{{ include "go-quai.name" $ }}
          port:
            name: ws
{{- end }}
