{{- define "go-quai.clusterIP" }}
- name: prime-http
  port: <HTTP>
  protocol: TCP
  targetPort: <HTTP>
- name: prime-ws
  port: <WS>
  protocol: TCP
  targetPort: <WS>
- name: prime-disc
  port: <DISC>
  protocol: UDP
  targetPort: <DISC>
{{- end }}
{{- define "go-quai.statefulset" }}
- image: {{ .Values.goQuai.image.name -}}:{{- .Values.goQuai.image.version }}
  imagePullPolicy: Always
  name: prime-go-quai
  command: ["./build/bin/go-quai", --$(NETWORK), "--syncmode", "full", "--http", "--http.vhosts=*", "--ws", "--mine", "--miner.threads", "1", <MINER_ETHERBASE>, "--http.addr", "0.0.0.0", "--http.api", "eth,net,web3,quai,txpool,debug", "--ws.addr", "0.0.0.0", "--ws.api", "eth,net,web3,quai,txpool,debug", "--port", $(TCP_PORT), "--http.port", $(HTTP_PORT), "--ws.port", $(WS_PORT), "--ws.origins=*", "--http.corsdomain=*", "--gcmode", "archive", <REGION>, <ZONE>, <SUB>, <DOM>]
  env:
  - name: COINBASE_ADDR
    valueFrom:
      secretKeyRef:
        name: {{ include "go-quai.name" $ }}
        key: PRIME_COINBASE_ADDR
  - name: TCP_PORT
    value: "<DISC>"
  - name: HTTP_PORT
    value: "<HTTP>"
  - name: WS_PORT
    value: "<WS>"
  - name: NETWORK
    value: {{ .Values.goQuai.network }}
  ports:
  - containerPort: <HTTP>
    name: prime-http
    protocol: TCP
  - containerPort: <WS>
    name: prime-ws
    protocol: TCP
  - containerPort: <DISC>
    name: prime-disc
    protocol: UDP
  volumeMounts:
  - mountPath: /root/.quai/
    name: {{ include "go-quai.name" $ }}
{{- end }}
