name: Dev Workflow
on:
  pull_request:
    types: [closed]
    branches: [ "main" ]
jobs:
  call-common-workflow:
    uses: dominant-strategies/quai-cicd/.github/workflows/deploy-dev-common.yml@main
    with:
      needs_build: true
      build_command: "make go-quai"
      needs_docker: false
      include_chart: false
      cloud_deploy: false
      skip_deploy: true
      update_version: false

    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY2 }}
      GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
